name: Format Capture

on:
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Format
        run: cargo fmt --all
      - name: Capture formatted files
        uses: actions/upload-artifact@v4
        with:
          name: canonical-rustfmt
          path: |
            src/symlink.rs
            src/symlink_unlink.rs
            tests/symlink_multiblock.rs
