name: Rustfmt diagnostic

on:
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all
      - uses: actions/upload-artifact@v4
        with:
          name: rustfmt-output
          path: |
            src/lib.rs
            src/path_collapse.rs
            tests/path_collapse.rs
